### ISSUE TITLE
Plugin not working any more with webpack 4

### ISSUE THREAD

**Issue by tzimmermann** [tomchentw/unused-files-webpack-plugin#20]
After upgrading from `webpack 3` to `4.1.1`, I get this error message during compiling:
```
compilation.fileDependencies.reduce is not a function
```

Which I traced back to this line:

https://github.com/tomchentw/unused-files-webpack-plugin/blob/master/src/index.js#L16

**Comment by tomchentw** [comment]
Released [v3.3.0](https://github.com/tomchentw/unused-files-webpack-plugin/releases/tag/v3.3.0)
