### ISSUE TITLE
Provide an higher abstraction around files: modules

### ISSUE THREAD

**Issue by oliviertassinari** [tomchentw/unused-files-webpack-plugin#9]
### Problem description

I'm building a multi-platform app. To split the implementation between different platform, I'm using the `server.js`, `browser.js`, `ios.js` and `android.js` file extension pattern.

It would be great if we could have a way to abstract away from the file notion.
In my use case, I'm considering all those files with different extensions as a single module.
That's that module I want to make sure is already use.

E.g. when building for the `browser` platform, some `.x.server.js` files might not be used, but that's expected.
### Cheap workaround

Provide an option to filter the `fileDepsMap` before looking for unused files.

I would be using this option to _normalize_ the file names (removing extensions).
On the other hand. I'm ignoring any platform extension with the existing `globOptions`.

**Comment by tomchentw** [comment]
You'll need different webpack config for different platform. In this case, I believe ignoring any other platform extension is reasonable, right?

**Comment by oliviertassinari** [comment]
Right, that's the approach I'm using on user-side (`globOptions.ignore`).
